# Generated by Django 5.0.6 on 2024-06-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appserver',
            old_name='channel',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='appserver',
            old_name='title',
            new_name='name',
        ),
    ]
