# Generated by Django 5.0.6 on 2024-06-13 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_channel_appserver_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appserver',
            old_name='mail',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='appserver',
            name='space',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
