# Generated by Django 5.0.6 on 2024-06-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_mail_appserver_activity_appserver_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='appserver',
            name='email',
            field=models.CharField(default='asas@gmail.ff', max_length=100),
        ),
    ]
